# Generated by Django 3.2.8 on 2021-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, verbose_name='RUT')),
                ('rut_dv', models.CharField(max_length=1, verbose_name='Digito Verificador')),
                ('nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('paterno', models.CharField(max_length=80, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=80, verbose_name='Apellido Materno')),
                ('telefono', models.IntegerField(verbose_name='Teléfono Móvil')),
                ('autorizado', models.BooleanField(verbose_name='Autorizado')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cli_cliente',
            },
        ),
    ]
