# Generated by Django 3.2.8 on 2021-11-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_categoria', models.CharField(max_length=30)),
                ('nom_categoria', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'ped_producto_categoria',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_comuna', models.CharField(blank=True, max_length=30, null=True)),
                ('nom_comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'ped_comuna',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Estado Pedido',
                'verbose_name_plural': 'Estados de Pedido',
                'db_table': 'ped_pedido_estado',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Producto',
                'verbose_name_plural': 'Tipos de Producto',
                'db_table': 'ped_producto_tipo',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, max_length=8, null=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
                ('rubro', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_representante', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PRODUCTOS.comuna')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'ped_proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=17, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('stock_critico', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PRODUCTOS.categoriaproducto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PRODUCTOS.proveedor')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PRODUCTOS.tipoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'ped_producto',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_orden', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Orden')),
                ('cant_productos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Productos')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('total_pedido', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Total Pedido')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PRODUCTOS.estadopedido')),
                ('productos', models.ManyToManyField(blank=True, null=True, to='PRODUCTOS.Producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'ped_pedido',
            },
        ),
    ]
