# Generated by Django 3.2.8 on 2021-11-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sub_total',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='PRODUCTOS.Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Pedido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_critico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
