# Generated by Django 3.2.8 on 2021-11-13 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0002_auto_20211112_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PRODUCTOS.proveedor'),
        ),
    ]
